// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  basicsSidebar: [{ type: "autogenerated", dirName: "01-podstawy" }],
  uxuiSidebar: [{ type: "autogenerated", dirName: "02-ux-ui" }],
  frontendSidebar: [{ type: "autogenerated", dirName: "03-frontend" }],
  backendSidebar: [{ type: "autogenerated", dirName: "04-backend" }],
  fullstackSidebar: [{ type: "autogenerated", dirName: "05-fullstack" }],
}

module.exports = sidebars
