// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  basicsSidebar: [{ type: "autogenerated", dirName: "010-podstawy" }],
  uxuiSidebar: [{ type: "autogenerated", dirName: "020-ux-ui" }],
  frontendSidebar: [{ type: "autogenerated", dirName: "030-frontend" }],
  backendSidebar: [{ type: "autogenerated", dirName: "040-backend" }],
  fullstackSidebar: [{ type: "autogenerated", dirName: "050-fullstack" }],
}

module.exports = sidebars
