// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  csFundamentalsSidebar: [{ type: "autogenerated", dirName: "01-informatyka" }],
  uxuiSidebar: [{ type: "autogenerated", dirName: "02-ux-ui" }],
  frontendSidebar: [{ type: "autogenerated", dirName: "03-frontend" }],
}

module.exports = sidebars
